[workspace]
members = ["crates/*"]

[workspace.dependencies]
rnix = { path = "../rnix-parser" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.82", features = ["unbounded_depth"] }
