[package]
name = "parser_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
ref_impl_parser = { path = "../ref_impl_parser" }
rnix_to_json = { path = "../rnix_to_json" }
serde_json = "1.0.82"
assert-json-diff = "2.0.2"
indoc = "1.0.6"
paste = "1.0.7"
