[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
ref_impl_parser = { path = "../ref_impl_parser" }
rnix_to_json = { path = "../rnix_to_json" }
rnix = { path = "../../../rnix-parser" }
