[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
ref_impl_parser = { path = "../ref_impl_parser" }
rnix_normalize = { path = "../rnix_normalize" }
rnix_ast = { path = "../rnix_ast" }
rnix = { path = "../../../rnix-parser" }
serde_json = "1.0.82"
