[package]
name = "rnix_to_json"
version = "0.1.0"
edition = "2021"

[dependencies]
# rnix = { git = "https://github.com/darichey/rnix-parser", branch = "typed-path-interpol" }
rnix = { path = "../../../rnix-parser" }
serde_json = "1.0.81"
ast = { path = "../ast" }
